packages:
 - packages/*

catalog:
  nuxt: "^3.13.2"
  "@vueuse/core": "^10.11.0"
  "@nuxtjs/tailwindcss": "^6.12.1"
  tailwindcss: "^3.4.4"
  vue: "latest"
  vue-router: "latest"
  'nuxt-svgo': '^4.0.6'