// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Manager } from "./Manager";
import type { MusicianWithPurpose } from "./MusicianWithPurpose";
import type { YearFromTo } from "./YearFromTo";

export type Band = { name: string, established_in: number, description: string, country_of_origin: string, members: Array<YearFromTo<MusicianWithPurpose>>, music_styles: Array<string>, instruments: Array<string>, links: Array<string>, managers: Array<YearFromTo<Manager>> | null, searching_for: Array<string>, };
