// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Band = { name: string, established_in: number, description: string, country_of_origin: string, members: Array<string | null>, music_styles: Array<string>, instruments: Array<string>, links: Array<string>, managers: Array<string | null> | null, searching_for: Array<string>, };
