// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserTypes } from "./UserTypes";

export type CreateUserPayload = { name: string, lastname: string, description: string, email: string, phone: string, phone_prefix: string, country: string, city: string, street: string, house_number: string, apartment: string | null, password: string, types: Array<UserTypes | null>, };
