// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateMusicianPayload = { user_id: string, stage_name: string, bands: Array<string | null>, skills: Array<string | null>, links: Array<string | null>, managers: Array<string | null> | null, open_to_collab_with: Array<string | null>, };
