// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Band } from "./Band";
import type { User } from "./User";
import type { YearFromTo } from "./YearFromTo";

export type Manager = { user: User, stage_name: string, commission: [number, number], bands: Array<YearFromTo<Band>>, categories_interested_in: Array<string>, };
