// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Manager = { user_id: string, stage_name: string, commission: Array<number>, bands: Array<string>, categories_interested_in: Array<string>, };
