// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Musician } from "./Musician";

export type MusicianWithPurpose = { musician: Musician, main_purpose: string, };
