// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Band } from "./Band";
import type { Manager } from "./Manager";
import type { User } from "./User";
import type { YearFromTo } from "./YearFromTo";

export type Musician = { id: string, user: User, stage_name: string, bands: Array<YearFromTo<Band> | null>, managers: Array<YearFromTo<Manager>> | null, links: Array<string | null>, skills: Array<string | null>, open_to_collab_with: Array<string | null>, };
