// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Band } from "./Band";
import type { Manager } from "./Manager";
import type { Skills } from "./Skills";
import type { User } from "./User";
import type { YearFromTo } from "./YearFromTo";

export type Musician = { user: User, stage_name: string, bands: Array<YearFromTo<Band>>, skills: Array<Skills>, links: Array<string>, managers: Array<YearFromTo<Manager>> | null, open_to_collab_with: Array<string>, };
