[package]
name = "mmatch_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.7"
chrono = "0.4.38"
diesel = { version = "2.2.4", features = ["postgres", "chrono"] }
diesel-derive-enum = { version = "2.1.0", features = ["postgres"] }
dotenvy = "0.15.7"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = {version = "1.40.0", features = ["full"]}
tower = "0.5.1"
tower-http = {version = "0.6.1", features = ["cors"]}
ts-rs = "10.0.0"
uuid = {version = "1.10.0", features = ["v4"]}
